#!/bin/bash

################################################################################
#
#  Possible command:
#
#    qsub run_learner -pe parallel 12  Comment to go in the output
#
################################################################################
echo "******************************************************************************"
echo $*
date
echo $HOST running $JOB_NAME.$JOB_ID
grep OPT flags
echo
echo "******************************************************************************"

cd ~/nlp/auto_parse
date
./learn.main eng_only pretty.csv ~/run_learner.t$JOB_ID.tex

date
echo $*
sed "s/runningTitle/$*/" ~/run_learner.t$JOB_ID.tex > ~/tmp
rm ~/run_learner.t$JOB_ID.tex
mv ~/tmp ~/run_learner.t$JOB_ID.tex
echo SCRIPT OVER
