#!/bin/bash

################################################################################
#
#  Possible command:
#
#    qsub run_learner -pe parallel 12  Comment to go in the output
#
################################################################################
cd ~/nlp/auto_parse
echo
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo "*"
echo  $* | sed "s/.*--comment//" | sed "s/.*-c//"| sed "s/^/*  /"
echo "*"
echo "*  " $HOST running $JOB_NAME.$JOB_ID
echo -n "*   "; grep OPT ~/nlp/auto_parse/flags|grep -v "#"|grep -v "CFLAGS"
echo -n "*   "; git log |head -1
echo -n "*   "; git log |head -3 |tail -1
echo "*"
echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
echo

date
./learn.main --latex=/home1/f/foster/run_learner.t$JOB_ID.tex $*
date
echo $*
sed "s/runningTitle/$*/" ~/run_learner.t$JOB_ID.tex > ~/tmp
rm ~/run_learner.t$JOB_ID.tex
mv ~/tmp ~/run_learner.t$JOB_ID.tex
echo SCRIPT OVER
